[package]
name = "yapl"
description = "A library for testing if numbers are prime, and getting the n prime"
version = "0.2.1"
authors = ["Bryant Conquest <bryant@paxavis.dev>"]
license = "MIT"

[dependencies]
